### ISSUE TITLE
[Frontend] Search Component

### ISSUE THREAD

**Issue by AlanBar13** [AlanBar13/bolxs-app-nextjs#12]

**Comment by manetoso** [comment]
I'll start working on this feature
I'm planning to use [Fuse.js](https://fusejs.io/demo.html) to search for information using fuzzy logic.

With this approach we will not need to use any library for Global State Management because the user will have displayed the Fuzzy list and when clicking on any element the app will redirect them to the Event Details Page.

**Comment by AlanBar13** [comment]
If you need an API call that provides something else you need just tell me and I work on it, Right now we have this call that accept a search string and will search title and tags over [here](https://bolxs-server.onrender.com/v1/api-docs/#/Events/searchExactEvents)

**Comment by manetoso** [comment]
With that endpoint call would be much easier.
I can use that when the user press enter in the input, because I'm using the data from the /events GET endpoint that it is call on the beginning to filter events when the user tap in the input.

When they just write, the app filters the events data:
<img width="1680" alt="Screenshot 2023-01-31 at 10 38 57 a m" src="https://user-images.githubusercontent.com/73187982/215823582-27f9f76c-5280-43b6-bf8b-3a7653d8b5e7.png">

When they press enter, the GET endpoint gets called and if no data is received promps this:
<img width="1680" alt="Screenshot 2023-01-31 at 10 39 24 a m" src="https://user-images.githubusercontent.com/73187982/215823702-fd9b1b27-e95c-4fff-95c3-bb6126ba4924.png">
